---
#tasks file for deploy-web-php
- name: "Install Docker"
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes

- name: "Copy files to srv"
  ansible.builtin.copy:
    src: ./
    dest: "{{ app_directory }}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: '0755'

- name: "Apply Nginx template conf"
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: Restart nginx
  
- name: "Start app using docker-compose"
  community.docker.docker_compose:
    project_src: "{{ app_directory }}"
    restarted: yes