
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    ports:
      - "80:80"
    restart: always

  php:
    container_name: php-web
    build:
      context: ./php
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db
    restart: always

  db:
    container_name: mysql-db
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always

volumes:
  db_data: